### ISSUE TITLE
lofi error

### ISSUE THREAD

**Issue by IoannisTM** [lime-desu/bin#2]
Hello,
Thanks for your nice scripts.
I have a question.
Does the lofi script works for you?

I get the below message, so wanted to make sure if that was just me 

> ./lofi-girl.sh: line 6: declare: -A: invalid option
> declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
> ./lofi-girl.sh: line 13: declare: -A: invalid option
> declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
> Playing freeCodeCamp code Radio...
>  (+) Audio --aid=1 (mp3 2ch 44100Hz)
> AO: [coreaudio] 44100Hz stereo 2ch floatp
> A: 00:00:00 / 00:00:05 (18%) Cache: 3.9s/139KB
> File tags:
>  icy-title: Emancipator - Wolf Drawn
> A: 00:00:02 / 00:00:06 (37%) Cache: 4.1s/148KB

thanks for the help

**Comment by Apocryphon-X** [comment]
To me it shows:

> Playing lofi hip hop radio - beats to relax/study to...
[ytdl_hook] ERROR: [youtube] jfKfPfyJRdk: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.
> 
> Exiting... (Errors when loading file)

- youtube-dl --version: `2021.12.17`

It only works with the FCC Radio

**Comment by Apocryphon-X** [comment]
Update: I managed to edit the script to make the youtube streams work at the cost of sacrificing FCC radio. P.S: I don't know why it doesn't work for you but it looks like you have an outdated version of bash or something (I say this because of the error you get from the `declare -A` command).

**Comment by Ioulan** [comment]
> Hello, Thanks for your nice scripts. I have a question. Does the lofi script works for you?
> 
> I get the below message, so wanted to make sure if that was just me
> 
> > ./lofi-girl.sh: line 6: declare: -A: invalid option
> > declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
> > ./lofi-girl.sh: line 13: declare: -A: invalid option
> > declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
> > Playing freeCodeCamp code Radio...
> > (+) Audio --aid=1 (mp3 2ch 44100Hz)
> > AO: [coreaudio] 44100Hz stereo 2ch floatp
> > A: 00:00:00 / 00:00:05 (18%) Cache: 3.9s/139KB
> > File tags:
> > icy-title: Emancipator - Wolf Drawn
> > A: 00:00:02 / 00:00:06 (37%) Cache: 4.1s/148KB
> 
> thanks for the help

The scripts works fine on me, what's your bash version? I believe the `declare -A` command is available on bash < 4.0, How about removing the `declare -A` keyword?

**Comment by Ioulan** [comment]
> To me it shows:
> 
> > Playing lofi hip hop radio - beats to relax/study to...
> > [ytdl_hook] ERROR: [youtube] jfKfPfyJRdk: Unable to extract uploader id; please report this issue on  [yt-dlp/yt-dlp/issues?q=](https://github.com/yt-dlp/yt-dlp/issues?q=sort%3Aupdated-desc) , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> > [ytdl_hook] youtube-dl failed: unexpected error occurred
> > Failed to recognize file format.
> > Exiting... (Errors when loading file)
> 
>     * youtube-dl --version: `2021.12.17`
> 
> 
> It only works with the FCC Radio

Hmm weird why there's yt-dlp in here?

**Comment by Apocryphon-X** [comment]
> Hmm weird why there's yt-dlp in here?

Haha I didn't realize it before but it looks like I was using an outdated version of yt-dlp (I simply uninstalled the version I had from apt and installed the pip version instead). 

Apparently mpv has as a dependency on yt-dlp when it has to retrieve an audio stream from youtube and that was the root cause of the problem.

Now I don't have to sacrifice FCC radio anymore.

**Comment by IoannisTM** [comment]
Thanks guys. 
It seems Apple being Apple was stuck at 3.2 bash.
And me being me I did not think about that :D 
I upgraded my bash to the latest version and now it works as expected

Thank you again for the help!
